### PR TITLE
MutationResult should be placed in insert.py instead of search.py

### PR DESCRIPTION
**Pull request by xiaocai2333**
Signed-off-by: xiaocai2333 <cai.zhang@zilliz.com>

### CODE REVIEW

**Comment by xiaocai2333** [comment]
see also #198

**Review by XuanYang-cn — COMMENTED** [review]
/lgtm

**Review by czs007 — CHANGES_REQUESTED** [review]
Please rename insert.py to mutation.py

**Review by czs007 — APPROVED** [review]

**Comment by XuanYang-cn** [comment]
fixes: #198

**Pull request merged**
