### PR TITLE
Fix small typo in documentation

### PR DESCRIPTION
**Pull request by scipe**
`descrition` => `description`

### CODE REVIEW

**Review by scsven — COMMENTED** [review]
/lgtm
/approve

**Comment by XuanYang-cn** [comment]
@scipe Looks like the robot is unhappy about the DCO status, please check the DCO details and fix it.

This is the last requirement for the robot to merge your PR.

Expecting your updates :smile_cat:

**Comment by scipe** [comment]
Hi @XuanYang-cn. I am sorry for that. Fixed.

**Pull request merged**
